version: '3'

# nginx, backend, frontend share the same "localhost"
# it's neccessary because files in minio must be reachable inside frontend container and developer's browser
# In real world you'll just use publicly available domain name
services:
  nginx:
    container_name: olios-nginx
    image: nginx:1.15-alpine
    depends_on:
      - backend
      - frontend
    # ports:
    #   - '8000:8000'
    volumes:
      - ./nginx_dev:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    network_mode: service:backend
    # networks:
    # - internal

  backend:
    ports:
      - '8000:8000'
      - '5111:5111'
      - '3000:3000'
    networks:
      - internal
  frontend:
    network_mode: service:backend
    # network_mode: host

networks:
  internal:
    driver: bridge
