# nginx, backend, frontend share the same "localhost"
# it's neccessary because files in minio must be reachable inside frontend container and developer's browser
# In real world you'll just use publicly available domain name
services:
  frontend:
    container_name: olios-frontend
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    command: sh -c 'npx nx dev frontend --verbose'
    ports:
      - '8000:8000' # for nginx
      - '5111:5111' # for backend
      - '3000:3000' # for frontend
    networks:
      - internal

  nginx:
    container_name: olios-nginx
    image: nginx:1.15-alpine
    depends_on:
      - frontend
      - backend
    # ports:
    #   - '8000:8000'
    volumes:
      - ./nginx_dev:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    network_mode: service:frontend
    # networks:
    # - internal

  backend:
    network_mode: service:frontend

networks:
  internal:
    driver: bridge
