# nginx, backend, storefront share the same "localhost"
# it's neccessary because files in minio must be reachable inside storefront container and developer's browser
# In real world you'll just use publicly available domain name
services:
  storefront:
    container_name: olios-storefront
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - node-modules:/usr/src/app/node_modules
    command: sh -c 'npx nx dev storefront --verbose'
    ports:
      - '8000:8000' # for nginx
      - '5111:5111' # for backend
      - '3000:3000' # for storefront
      - '4200:4200' # for admin panel
    networks:
      - internal

  admin-panel:
    container_name: olios-admin-panel
    build:
      context: .
      target: deps
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app/
      - node-modules:/usr/src/app/node_modules
    command: sh -c 'npx nx serve admin-panel'
    network_mode: service:storefront

  nginx:
    container_name: olios-nginx
    image: nginx:1.15-alpine
    depends_on:
      - storefront
      - admin-panel
      - backend
    # ports:
    #   - '8000:8000'
    volumes:
      - ./nginx_dev:/etc/nginx/conf.d
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    network_mode: service:storefront
    # networks:
    # - internal

  backend:
    network_mode: service:storefront

networks:
  internal:
    driver: bridge

volumes:
  node-modules:
    driver: local
