version: '3'

services:
  frontend:
    container_name: olios-frontend
    build:
      context: ./apps/frontend
      target: deps
    # ports are published at root docker-compose.yaml
    # ports:
    #   - '3000:3000'
    command: sh -c 'npm run dev'
    volumes:
      - ./apps/frontend:/app
    depends_on:
      - backend
