---
- name: Setup user
  hosts: olios_shop
  remote_user: root
  gather_facts: false

  tasks:
    - name: Create user ansible
      ansible.builtin.user:
        name: '{{ user }}'
        password: '{{ user_password | password_hash("sha512") }}'
        groups: sudo
        shell: /bin/bash
        create_home: yes
        state: present

    - name: Set up authorized keys
      authorized_key:
        user: '{{ user }}'
        key: '{{ item }}'
      with_file:
        - '{{ public_key_path }}'
