---
- name: Setup hosts
  hosts: olios_shop
  remote_user: '{{ user }}'
  gather_facts: false

  vars:
    home_dir: '/home/{{ user }}'
    app_folder: olios
    app_dir: '{{ home_dir }}/olios-monolith'

  tasks:
    - name: Copy folder structure
      ansible.builtin.file:
        path: '{{ app_dir }}/{{ item.path }}'
        state: directory
        mode: '{{ item.mode }}'
      with_community.general.filetree: '{{ app_folder }}/'
      when: item.state == 'directory'

    - name: Copy files
      ansible.builtin.template:
        src: '{{ item.src }}'
        # Your template files should be stored with a .j2 file extension,
        # but should not be deployed with it. splitext|first removes it.
        dest: '{{ app_dir }}/{{ item.path | splitext | first }}'
        mode: '{{ item.mode }}'
      with_community.general.filetree: '{{ app_folder }}/'
      when: item.state == 'file'

    - name: Create docker network
      community.docker.docker_network:
        name: reverse-proxy
        internal: false
        state: present

    - name: Run docker compose for Backend
      ansible.builtin.shell:
        chdir: '{{ app_dir }}/backend'
        cmd: 'docker compose pull && docker compose up -d'

    - name: Run docker compose for Nginx and Frontend
      ansible.builtin.shell:
        chdir: '{{ app_dir }}'
        cmd: 'docker compose pull && docker compose up -d'
