---
- name: Setup hosts
  hosts: olios_shop
  remote_user: '{{ user }}'
  gather_facts: false

  vars:
    home_dir: '/home/{{ user }}'
    app_folder: olios-monolith
    app_dir: '{{ home_dir }}/{{ app_folder }}'

  tasks:
    - name: Create docker network
      community.docker.docker_network:
        name: reverse-proxy
        internal: false
        state: present

    - name: Run docker compose for Backend
      ansible.builtin.shell:
        chdir: '{{ app_dir }}/backend'
        cmd: 'docker compose pull && docker compose up -d'

    - name: Run docker compose for Nginx and Frontend
      ansible.builtin.shell:
        chdir: '{{ app_dir }}'
        cmd: 'docker compose pull && docker compose up -d'
